name: Deploy by self-hosted runner

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Test runner
        run: echo 123 > ~/test.txt
      #- name: Install dependencies
      #  run: yarn install --frozen-lockfile

      #- name: Build app
      #  run: yarn build
